Add utility functions for rotation conventions
JuliaEarth/GeoStatsBase.jl pull request #98
Opened 2021-12-08 23:05 UTC by fnaghetini

This PR addresses issue [JuliaEarth/GeoStats.jl#201](https://github.com/JuliaEarth/GeoStats.jl/issues/201) to add utility functions for the following software conventions using `EulerAngles` from `ReferenceFrameRotations.jl` package:
- Datamine (`DatamineAngles`)
- GSLIB (`GslibAngles`);
- Vulcan (`VulcanAngles`).

Since **Geological convention** (adopted by these softwares) is different from the **Math convention** (adopted by `ReferenceFrameRotations.jl`), we must consider a 90° offset in the azimuth (first rotation, around Z). Check the sketch below:

![image](https://user-images.githubusercontent.com/63740520/145303926-085489da-1927-4bbb-ac69-360c64c12147.png)

Different ellipsoids generated using `DatamineAngles` were compared with ellipsoids created in Studio RM (Datamine sotfware) and, visually, everything seems to be fine. Moreover, converting between those three software conventions is a simple matter of inverting signals.

Look forward to feedback on this!

Franco

2021-12-09 00:11 UTC, juliohm requested changes
That is an awesome PR @fnaghetini ❤️ Love the references, the consistency in the code and the auxiliary image to help review it. Attached a few comments of improvement.

After you address the comments, we will probably need to add ReferenceFrameRotations.jl to the Project.toml of the package using the pkg manager and will need a few tests in the test suite.

2021-12-09 00:11 UTC, juliohm commented on src/GeoStatsBase.jl
> +include("rotations.jl")
Awesome, please move this include to before the plotrecipes.jl include.

2021-12-09 00:11 UTC, juliohm commented on src/GeoStatsBase.jl
>    groupby
Missing comma here.

2021-12-09 00:11 UTC, juliohm commented on src/rotations.jl
> +
We can't add a white line between the docstring and the struct otherwise Julia won't connect the two.

2021-12-09 00:11 UTC, juliohm commented on src/rotations.jl
> +
Same here.

2021-12-09 00:11 UTC, juliohm commented on src/rotations.jl
> +
And here.

2021-12-09 00:11 UTC, juliohm commented on src/rotations.jl
> +end
Please write these as oneliners:

```julia
DatamineAngles(...) = EulerAngles(...)
```

2021-12-13 14:14 UTC, juliohm commented
Hi @fnaghetini, any progress with the tests for this PR?

2021-12-13 16:31 UTC, fnaghetini commented
> Hi @fnaghetini, any progress with the tests for this PR?

Not yet, @juliohm. I'll make it ASAP.

2021-12-13 23:03 UTC, juliohm approved these changes

2021-12-13 23:12 UTC, juliohm commented
The tests are failing due to unrelated reasons. We are currently refactoring some of the code in Meshes.jl and the errors are caused by that. I will merge the PR, thanks for the additions! 💯 :)

2021-12-13 23:12 UTC, merged